import os
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from sqlalchemy import or_

from app.core.database import get_db
from app.core.config import settings
from app.models.models import Application, Certificate, Enterprise, EnterpriseAddress

router = APIRouter(prefix="/public", tags=["Public Verification & Portal Utilities"])

@router.get("/verify/{udyam_number}")
def public_verify_udyam(
    udyam_number: str,
    db: Session = Depends(get_db)
):
    cert = db.query(Certificate).filter(
        Certificate.udyam_registration_number == udyam_number.strip()
    ).first()

    if not cert:
        # Also check application table
        app = db.query(Application).filter(
            Application.udyam_registration_number == udyam_number.strip()
        ).first()
        if not app or not app.certificate:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No registration record found for Udyam number: {udyam_number}"
            )
        cert = app.certificate

    return {
        "is_valid": True,
        "is_simulation": True,
        "disclaimer": "This is a prototype simulation record generated by the SIH26130 platform. It does NOT represent an official Government of India registration.",
        "registration_details": {
            "udyam_registration_number": cert.udyam_registration_number,
            "enterprise_name": cert.enterprise_name,
            "organisation_type": cert.organisation_type,
            "enterprise_type": cert.enterprise_type,
            "major_activity": cert.major_activity,
            "state": cert.state,
            "district": cert.district,
            "registration_date": cert.issue_date.strftime("%d %B %Y"),
            "status": "ACTIVE_SIMULATION"
        }
    }

@router.get("/certificate/{udyam_number}/pdf")
def download_certificate_pdf(
    udyam_number: str,
    db: Session = Depends(get_db)
):
    cert = db.query(Certificate).filter(
        Certificate.udyam_registration_number == udyam_number.strip()
    ).first()

    if not cert or not cert.pdf_path or not os.path.exists(cert.pdf_path):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Certificate PDF not found or has not been generated yet."
        )

    return FileResponse(
        path=cert.pdf_path,
        filename=f"{cert.udyam_registration_number}.pdf",
        media_type="application/pdf"
    )

@router.get("/track/{identifier}")
def public_track_application(
    identifier: str,
    db: Session = Depends(get_db)
):
    clean_id = identifier.strip()
    app = db.query(Application).filter(
        or_(
            Application.application_number == clean_id,
            Application.udyam_registration_number == clean_id,
            Application.external_reference_id == clean_id
        )
    ).first()

    if not app:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No application found with identifier: {clean_id}"
        )

    ent_name = app.enterprise.name if app.enterprise else "—"
    state_name = app.address.state if app.address else "—"

    timeline = []
    for h in app.status_history:
        timeline.append({
            "status": h.new_status,
            "comments": h.comments,
            "date": h.created_at
        })

    return {
        "application_number": app.application_number,
        "enterprise_name": ent_name,
        "enterprise_type": app.enterprise_type,
        "status": app.status,
        "state": state_name,
        "submission_date": app.submission_date,
        "udyam_registration_number": app.udyam_registration_number,
        "timeline": timeline
    }

@router.get("/schema")
def get_public_form_schema():
    from app.routers.integrations import get_dynamic_form_schema
    return get_dynamic_form_schema()
